#!/usr/bin/env python3
"""
generate_html.py — PlatformIO pre-build/upload script
Compresses data/index.html → include/dashboard_gz.h before every build.
Registered via extra_scripts in platformio.ini.
"""

import gzip, os, sys

Import("env")

SRC  = os.path.join(env.subst("$PROJECT_DIR"), 'data', 'index.html')
DEST = os.path.join(env.subst("$PROJECT_DIR"), 'include', 'dashboard_gz.h')

def generate(*args, **kwargs):
    if not os.path.exists(SRC):
        print(f"[HTML] WARNING: {SRC} not found, skipping")
        return

    with open(SRC, 'rb') as f:
        raw = f.read()

    compressed = gzip.compress(raw, compresslevel=9)
    ratio = (1 - len(compressed) / len(raw)) * 100

    lines = [
        '// AUTO-GENERATED by generate_html.py — do not edit manually',
        f'// Source     : data/index.html  ({len(raw):,} bytes)',
        f'// Compressed : {len(compressed):,} bytes  ({ratio:.0f}% smaller)',
        '#pragma once',
        f'const uint32_t DASHBOARD_HTML_LEN = {len(compressed)};',
        'const uint8_t  DASHBOARD_HTML_GZ[] PROGMEM = {',
    ]
    for i in range(0, len(compressed), 16):
        chunk = compressed[i:i+16]
        lines.append('  ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',')
    lines.append('};')

    with open(DEST, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"[HTML] data/index.html → include/dashboard_gz.h  "
          f"({len(raw):,} → {len(compressed):,} bytes, {ratio:.0f}% saved)")

# Hook into every relevant action
env.AddPreAction("build",      generate)
env.AddPreAction("buildprog",  generate)
env.AddPreAction("upload",     generate)
env.AddPreAction("program",    generate)