#!/usr/bin/env python3
"""
generate_html.py — PlatformIO pre-build script
Reads data/index.html, gzip compresses it, writes include/web_pages.h
and regenerates the PAGE_DASHBOARD_GZ byte array in src/web_pages.cpp.

Runs automatically before every build via extra_scripts in platformio.ini.
Can also be run manually: python generate_html.py
"""

import gzip, os, re

try:
    Import("env")
    PROJECT_DIR = env.subst("$PROJECT_DIR")
    IS_PIO = True
except:
    PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
    IS_PIO = False

SRC_HTML   = os.path.join(PROJECT_DIR, 'data', 'index.html')
DEST_CPP   = os.path.join(PROJECT_DIR, 'src',  'web_pages.cpp')

def generate(*args, **kwargs):
    if not os.path.exists(SRC_HTML):
        print(f"[HTML] WARNING: {SRC_HTML} not found — skipping")
        return

    with open(SRC_HTML, 'rb') as f:
        raw = f.read()

    compressed = gzip.compress(raw, compresslevel=9)
    ratio = (1 - len(compressed) / len(raw)) * 100

    # Read existing web_pages.cpp to preserve OTA pages
    with open(DEST_CPP, 'r', encoding='utf-8') as f:
        existing = f.read()

    # Extract everything from "// ── OTA pages" onwards
    ota_marker = '// ── OTA pages'
    ota_idx = existing.find(ota_marker)
    ota_section = existing[ota_idx:] if ota_idx != -1 else ''

    # Build new file
    lines = []
    lines.append('/*')
    lines.append(' * web_pages.cpp — AUTO-GENERATED by generate_html.py')
    lines.append(f' * Source: data/index.html ({len(raw):,} bytes)')
    lines.append(f' * Compressed: {len(compressed):,} bytes ({ratio:.0f}% smaller)')
    lines.append(' * Do not edit the PAGE_DASHBOARD_GZ section manually.')
    lines.append(' */')
    lines.append('')
    lines.append('#include "web_pages.h"')
    lines.append('')
    lines.append('#define UTIL_STYLE \\')
    lines.append('    "background:#0a0e14;color:#c0cfe0;font-family:monospace;padding:40px"')
    lines.append('#define UTIL_BTN \\')
    lines.append('    "background:#00d4ff;color:#0a0e14;border:none;" \\')
    lines.append('    "padding:10px 24px;font-family:monospace;font-size:1rem;" \\')
    lines.append('    "cursor:pointer;border-radius:4px"')
    lines.append('#define UTIL_BACK \\')
    lines.append("    \"<p style='margin-top:24px'>\" \\")
    lines.append("    \"<a href='/' style='color:#00d4ff;text-decoration:none'>&#8592; Back</a></p>\"")
    lines.append('')
    lines.append('// ── Dashboard (gzip compressed) ─────────────────────────────────────────────')
    lines.append(f'// Original: {len(raw):,} bytes  →  Compressed: {len(compressed):,} bytes')
    lines.append(f'const uint32_t PAGE_DASHBOARD_LEN = {len(compressed)};')
    lines.append('const uint8_t  PAGE_DASHBOARD_GZ[] PROGMEM = {')
    for i in range(0, len(compressed), 16):
        chunk = compressed[i:i+16]
        lines.append('  ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',')
    lines.append('};')
    lines.append('')
    lines.append(ota_section.rstrip())
    lines.append('')

    result = '\n'.join(lines) + '\n'
    with open(DEST_CPP, 'w', encoding='utf-8') as f:
        f.write(result)

    print(f"[HTML] data/index.html → src/web_pages.cpp  "
          f"({len(raw):,} → {len(compressed):,} bytes, {ratio:.0f}% saved)")

if IS_PIO:
    env.AddPreAction("build",     generate)
    env.AddPreAction("buildprog", generate)
    env.AddPreAction("upload",    generate)
    env.AddPreAction("program",   generate)
else:
    generate()
